### ISSUE TITLE
[gtk3] New shortcuts shown that don't work

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#191]
gtk3 branch only:

1\. Right-click on `AVAILABLE CONNECTIONS` or an already defined connection in the left-hand bar.

Two entries are `Import connection(s)... Ctrl+O` and `Execute in New Cluster... Ctrl+N`. Their shortcuts don't work. These two entries don't have shortcuts shown in gtk2. [The remaining shortcuts that are also shown in gtk2 (e.g. `Clone connection Ctrl+D`) work as expected.]

2\. Launch a terminal connection. Right-click on its tab label (above the terminal).

Some entries show a shortcut, such as `Close terminal Ctrl+W` and `Close ALL terminals Ctrl+W`. (Also notice the conflict.) These shortcuts don't work. The gtk2 version doesn't display any shortcuts here.

**Comment by gfrenoy** [comment]
1) Looks like if you have stockicon set to "gtk-open" or "gtk-new", it now assumes you want to have Ctrl+O and Ctrl+N as shortcuts ?  I forced those entries to have no shortcut.

2) Same with "gtk-close" ; moreover shortcuts exist for those two actions (Ctrl+F4 and Ctrl+Shift+F4).

Will both be fixed by the next commit.

**Comment by egmontkob** [comment]
Thanks – although _some_ invalid shortcuts are still shown for me in the terminal's tab label's right-click menu. Namely Ctrl+F/S/C for Find, Save session log and Clone connection. Also Ctrl+N for Add to cluster -> New cluster.

**Comment by gfrenoy** [comment]
I chased all gtk-open, gtk-save, gtk-find, gtk-copy & gtk-new ; hope I did not miss one.

Thanks for your sharp eyes :)
